[package]
name = "janata-worker-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
janata-api-contract = { path = "../api-contract" }
janata-domain = { path = "../domain" }
serde_json.workspace = true
worker = "=0.8.5"
